name: action-cache-api-shim
description: >-
  This action will let you use other actions/tools that need access to the
  legacy GHA Cache Service v1 API.
author: Jashandeep Sohi
# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: layers
  color: red

inputs:
  require-v2:
    description: >-
      Fail if GHA Cache Service v2 is not available on the runner. By default,
      it will simply skip setting up the shim, but still report a success.
    required: false
    default: "false"

runs:
  using: node20
  main: dist/index.js
