FROM busybox:1.37.0

RUN echo -n 1 >> out
RUN echo -n 2 >> out
RUN echo -n 3 >> out
RUN echo -n 4 >> out
RUN echo -n 5 >> out
RUN echo -n 6 >> out
RUN echo -n 7 >> out
RUN echo -n 8 >> out
RUN echo -n 9 >> out
RUN cat out
ARG CACHEBUST
RUN test "$(sha256sum out)" = "15e2b0d3c33891ebb0f1ef609ec419420c20e320ce94c65fbc8c3312448eb225  out"
