name: Continuous Integration

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        uses: ./

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            network=host

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile.test
          tags: user/app:latest
          cache-from: type=gha,url=${{ env.ACTIONS_CACHE_URL }}
          cache-to: type=gha,mode=max,url=${{ env.ACTIONS_CACHE_URL }}
