name: Continuous Integration

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  test-docker:
    name: Test Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        uses: ./
        with:
          require-v2: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            network=host

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile.test
          tags: user/app:latest
          cache-from: type=gha,url=${{ env.ACTIONS_CACHE_URL }}
          cache-to: type=gha,mode=max,url=${{ env.ACTIONS_CACHE_URL }}
          build-args: |
            CACHEBUST=${{ github.sha }}-${{ github.run_number }}-${{ github.run_attempt }}

  test-magic-nix-cache:
    name: Test Magic Nix Cache
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        uses: ./
        with:
          require-v2: true

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@v8
        with:
          source-tag: v0.1.3
      - name: Run nix build
        run: |-
          set -ex
          nix build .#ci-test-cache-one
          nix build .#ci-test-cache-two
          test "$(cat result/message)" = "First one: Done"
