name: Continuous Integration

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Patch for local testing
        run: |-
          # Pre is not supported with "uses: ./", which is stupid
          # But since we're not doing anything in main anyways, this will work
          yq --inplace '(.runs.main = .runs.pre) | del(.runs.pre)' action.yml

      - name: Test Local Action
        uses: ./
        with:
          require-v2: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            network=host

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile.test
          tags: user/app:latest
          cache-from: type=gha,url=${{ env.ACTIONS_CACHE_URL }}
          cache-to: type=gha,mode=max,url=${{ env.ACTIONS_CACHE_URL }}
