name: Release

on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if:
      github.event_name == 'release' &&
      startsWith(github.event.release.tag_name, 'v')

    steps:
      - name: Update semver major & minor branches
        uses: actions/github-script@v7
        with:
          script: |-
            const tagName = context.payload.release.tag_name;

            if (!(new RegExp(/^v\d+[.]\d+[.]\d+$/)).test(tagName)) {
              core.setFailed("Tag is not semver");
              return
            }

            const [x, y, z] = tagName.slice(1).split(".");

            for (const elm of [`${x}`, `${x}.${y}`]) {
              const ref = `refs/heads/v${elm}`;
              try {
                await github.rest.git.createRef({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  ref: ref,
                  sha: context.sha,
                });
              } catch (error) {
                await github.rest.git.updateRef({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  ref: ref,
                  sha: context.sha,
                  force: true,
                });
              }
            }
